version: "3.8"

services:
  app:
    container_name: nokia-upvoter
    image: nokia-upvoter
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000