version: "3.8"

services:
  app:
    container_name: hachaton-frontend
    image: hachaton-frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000